# Generated by Django 4.2 on 2023-04-15 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_movie_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="user",
            new_name="order",
        ),
    ]
